---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/homelab
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
