apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  replicas: 1
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
      containers:
        - name: ntfy
          image: binwiederhier/ntfy
          args:
            - serve
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NTFY_AUTH_USERS
              valueFrom:
                secretKeyRef:
                  key: NTFY_AUTH_USERS
                  name: ntfy-users
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy/server.yml
              subPath: server.yml
              readOnly: true
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: config
          configMap:
            name: ntfy
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
