---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ntfy
  - namespace.yaml
  - ingress.yaml
configMapGenerator:
  - name: ntfy
    files:
      - server.yml
namespace: ntfy
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: ntfy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 25Mi
          limits:
            cpu: 10m
            memory: 50Mi
