apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1m
  path: ./kubernetes/infrastructure/homelab/kyverno
  healthCheckExprs:
    - apiVersion: kyverno.io/v1
      kind: ClusterPolicy
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kyverno
