apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  dependsOn:
    - name: kyverno
      namespace: kyverno
  healthCheckExprs:
    - apiVersion: kyverno.io/v1
      kind: ClusterPolicy
      failed: metadata.name == 'longhorn-add-nixos-path' && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: metadata.name == 'longhorn-add-nixos-path' && status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  wait: true
  interval: 1m0s
  path: ./kubernetes/infrastructure/homelab/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: longhorn-system
