apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  dependsOn:
    - name: monitoring
      namespace: monitoring
  interval: 1m
  path: ./kubernetes/infrastructure/homelab/sealed-secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: sealed-secrets
