creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - age1v2p6sy6p82r93ft4zpfv8qwqz29pf73vglk44t3ge3jtwsqcz4fqj33en7 # ops
          - age14ucjne9933qermmvns6s7cfxvd9t90j7p7985f79hkerdna83feqqzr2ek # murtaza
