---
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - age1q0mwgq0yhwykr4u2zsy8khy7zxjne02ed9spwfa8gpqv5kfddcyq4vm7ld # murtaza
          - age132a8fc6kvykvptnahl8enxc0xue0qa0gv6nw3nln27lu8tspcfusyy776e # scout
