extends: default
ignore:
- kubernetes/clusters/**/flux-system/
- secrets.yaml
rules:
  indentation:
    indent-sequences: false
  line-length:
    ignore: "*"
  comments:
    min-spaces-from-content: 1
  document-start: disable
