---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: cert-manager
spec:
  interval: 10m0s
  path: ./infrastructure/homelab/cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager-controller
  interval: 10m0s
  path: ./infrastructure/homelab/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
