apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synapse-postgres-credential
  namespace: synapse
spec:
  encryptedData:
    password: AgBbjHrSqqUH3vLsborWDqAyZfwrjai9KHusrtNCHe3PzNZJjUxjNSC8YDMSMOsAlh+S3VCPa2rTuXPf3t9iVzIYm/tglB58vPc3AhFUwT8dLx47j6zgqmG+kvAIpW8IrRnayhmYGxn58fRhG0p9BvKHhB0pJNvAsXQpLegb9YRyjos4eZo3tSvHQnTTPCfjvrEl3qAEXa0D6DywBxyP8YPlj4rxNaEAMW4HTNrz4qm4V0palLe+/B+til9hjDRzNAzVkimaNMo9Ryqc+wy7JsRbXs/pyjw7h44MpGDgP6R6CSaqMdCji2QQlnH5xY8eDHz6RODGkZNvc8UZMW1mdXuebE1OVY7FwpvHRJ8AURv9JKqzkhHZGya2Zj/Xwb3mBtStsyvlSbWmJwW+NFJisKSgwj1AK4xq9GRTm0+KtECQI5j0x+ZqXffBd36OGLweuCd6OcGDOosUL/qpuyjUsvQ5vW19KaTO6DupYO6V8qMmF6URT17BGMyVPKdiWRhvVinzBC0x0hBdl0iFyz7Dh98114Quc5CylfEwTQTowEyObjM79Ed3wIQB3e6x/16eEn+2tcpZj4PNF7pl7y+fby10L2W871NNiH5/paRlUQu6BVaZMgbTsGODu2njhusWniORp9ngRQ0Rmu2b9J0E8rM+S2OHwkkHfp6ELhVRKKpWsGOh3OHJ2IXukJnDhcLD5kNZEgfsGDmzQ6dfizXQOqJ28MSLbOPNhL99ld9Q/tCEIKwvWX/Xnp6IqIg/dD1t9LA=
  template:
    metadata:
      name: synapse-postgres-credential
      namespace: synapse
    type: Opaque
