# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-users
spec:
  encryptedData:
    NTFY_AUTH_USERS: AgCVDbNm1uAnnWMmcrhcZixqkLn9lG4FQezGPsJnCVcajvuQwHzjXf3xPYiZcticTugm+8Gf2ymxc811KEBMIGRyHVF4EmyeeAMyBnoSMsqKyBpQdkKs8/U7rTOzn1OmvORzs1iKNRKTfZpRpNbJ09wG61YTgxfYnTic4jF+dFltYlI7FOE3+jZ016KUv5eKqL9oZcAbqK8YGNMZPaIGh3Z33C+iQVLkh+w6gfpUhQ0t2CuzO/TMi8eAfS/BA5kXzh7Fq0sz7SHSCdSlpuPUzBvY0/irsAdSHfYTp4V9VI60GsaRzcTq3O29j+3S+8HHdMtaM7uSW7XlfBIhmPLXlrGh84hyOD5LWZKmfB7Opf/sH2IDpVlSnF72Ib2+nv3TQVw5PlCStcmRJ6skPGjF1f0a7z3HHZtOoiAiUCvNwr3zlgQ12FHo/9EhatXUNzMowm2CBgTLCxhfmfNl36qLfj8Sf2b3+XRSh2uKnGjuelw0/Vqas1oqkRJnJgdXeoKTPwshU0n2/JxOFaIfGKeqTJ1N8Kv3KkGf4pxUTbc8Nb5PJ/4IggeGDbwr85kRTNr+Z0o9iuuN9k58ctpUB8SLpNcvWiZQJ5+42sVOgiSvtk97bmuWt2yMdbmv2kpcCIx1ksPvCVON3W9W4ze3egQkrd0PxLnTcc4L5cdaZKH5ycrDV+30jxd4JLFJl5YAyocPWhbzu7WXABqprs0jukk0xZJ+xxqHO0FPlmy+34+EUPrRhxbB34hwt6rPnPTyEFZ/rQH77I4jFz3GDH7cviKYQtBdYTJryeBFJl6pQakp15D1/FovUgfoQydKJwKyEuK5s4sjha4+lKwcNYZ9dICDLq0awbgWQCbposPsFqrKwg/TPQlkzdwIhPztoon6Jtsqsd9WU9JXN/n+RCri
  template:
    metadata:
      name: ntfy-users
    type: Opaque
