apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ntfy
  labels:
    release: monitoring-kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: ntfy
