---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ .Release.Name }}"
  type: {{ .Values.service.type | default "LoadBalancer" | quote }}
  ports:
    - name: minecraft
      protocol: UDP
      port: 19132
      targetPort: bedrock
      nodePort: {{ .Values.service.nodePort }}
