apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: murtaza@murtazau.xyz
    # name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
