---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertfy
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./helm
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: alertfy
  dependsOn:
    - name: sealed-secrets
      namespace: sealed-secrets
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 10m0s
  values:
    replicaCount: 1
    resources:
      requests:
        memory: 15Mi
        cpu: 10m
      limits:
        memory: 30Mi
        cpu: 10m
    envSecretName: alertfy
    config:
      hook:
        auth:
          enable: false
        log:
          level: "info" # possible values: "debug", "info", "warn", "error"
          format: "json" # possible values: "text", "json"
        terminationGracePeriod: 0
      ntfy:
        baseUrl: "https://ntfy.murtazau.xyz"
        auth:
          enable: true
        notification:
          topic: "alertmanager"
          priority: |
            Status == "firing" ? "urgent" : "default"
          tags:
            - tag: "rotating_light,construction"
              condition: |
                Status == "firing"
            - tag: "white_check_mark,confetti_ball"
              condition: |
                Status == "resolved"
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
          description: |
            {{ index .Annotations "description" }}
