---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: alertfy
  namespace: monitoring
spec:
  interval: 10m0s
  ref:
    semver: '>=0.2.0'
  url: https://github.com/murtaza-u/alertfy
