---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: default
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ./charts/ntfy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    config:
      auth:
        defaultAccess: deny-all
      baseUrl: https://ntfy.example.com
      log:
        format: json
        level: info
      metrics:
        enable: true
      upstreamBaseUrl: https://ntfy.sh
      webRoot: disable
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enable: true
      host: ntfy.murtazau.xyz
      ingressClassName: traefik
      tls:
        enable: true
        secretName: ntfy-cert
    resources:
      limits:
        cpu: 70m
        memory: 100Mi
      requests:
        cpu: 40m
        memory: 70Mi
    storageSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
