apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
  server.yml: |
    base-url: "{{ .Values.config.baseUrl }}"
    listen-http: "{{ .Values.config.listenAddr }}"

    # caching
    cache-file: /data/cache.db
    cache-duration: "{{ .Values.config.cache.duration }}"
    cache-startup-queries: "{{ .Values.config.cache.startupQueries }}"
    cache-batch-size: {{ .Values.config.cache.batchSize }}
    cache-batch-timeout: "{{ .Values.config.cache.batchTimeout }}"

    # auth
    auth-file: /data/users.db
    auth-default-access: "{{ .Values.config.auth.defaultAccess }}"
    auth-startup-queries: "{{ .Values.config.auth.startupQueries }}"

    behind-proxy: true

    # attachments
    attachment-cache-dir: /data/attachments
    attachment-total-size-limit: "{{ .Values.config.attachment.totalSizeLimit }}"
    attachment-file-size-limit: "{{ .Values.config.attachment.fileSizeLimit }}"
    attachment-expiry-duration: "{{ .Values.config.attachment.expiryDuration }}"

    manager-interval: "{{ .Values.config.managerInterval }}"

    {{- if .Values.config.disallowedTopics }}
    disallowed-topics:
      {{- range .Values.config.disallowedTopics }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}

    web-root: "{{ .Values.config.webRoot }}"

    enable-signup: {{ .Values.config.enableSignup }}
    enable-login: {{ .Values.config.enableSignup }}
    enable-reservations: {{ .Values.config.enableReservations }}

    upstream-base-url: "{{ .Values.config.upstreamBaseUrl }}"
    upstream-access-token: "{{ .Values.config.upstreamAccessToken }}"

    message-size-limit: "{{ .Values.config.messageSizeLimit }}"
    message-delay-limit: "{{ .Values.config.messageDelayLimit }}"

    global-topic-limit: {{ .Values.config.globalTopicLimit }}

    # visitor
    visitor-subscription-limit: {{ .Values.config.visitor.subscriptionLimit }}
    visitor-request-limit-burst: {{ .Values.config.visitor.requestLimitBurst }}
    visitor-request-limit-replenish: "{{ .Values.config.visitor.requestLimitReplenish }}"
    visitor-request-limit-exempt-hosts: "{{ .Values.config.visitor.requestLimitExemptHosts }}"
    visitor-message-daily-limit: {{ .Values.config.visitor.messageDailyLimit }}
    visitor-attachment-total-size-limit: "{{ .Values.config.visitor.attachmentTotalSizeLimit }}"
    visitor-attachment-daily-bandwidth-limit: "{{ .Values.config.visitor.attachmentDailyBandwidthLimit }}"
    visitor-subscriber-rate-limiting: {{ .Values.config.visitor.subscriberRateLimiting }}

    # prometheus metrics
    enable-metrics: {{ .Values.config.metrics.enable }}
    metrics-listen-http: ":9090"

    # logging
    log-level: "{{ .Values.config.log.level }}"
    {{- if .Values.config.log.levelOverrides }}
    log-level-overrides:
      {{- range .Values.config.log.levelOverrides }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
    log-format: "{{ .Values.config.log.format }}"
    log-file: "{{ .Values.config.log.file }}"
