apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: "{{ .Release.Namespace }}"
spec:
  type: ClusterIP
  selector:
    app: ntfy
  ports:
    - name: http-ntfy
      protocol: TCP
      port: 80
      targetPort: http-ntfy
    {{- if .Values.config.metrics.enable }}
    - name: metrics-ntfy
      protocol: TCP
      port: 9090
      targetPort: metrics-ntfy
    {{- end }}
