apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCvnqDGEwKZnLFqwyOZbKrr33e1gfYHH2ktz7Ig0BFjqoGj8tqEduqH/uQr+zlQ4BeAWMu8sSoOetVsqEBWuW/N8pANTHgfuRdO5DHccFWUXBjRVi8l5D/eCS9prlGk9GlN98rpGJo2PVCQ416KcEEDJ+cp8CQU4UrQw400Z+V+MpnZJEr2gANozwEU9DtTjTX9WEpGGbHy7oDRUmffuu4ctA4JqgxNwl4JQAnb5tJcfILtHoXs5HxmKkpZ7o33cO6Ru67NrrcE+j68aa8hk3IrGsxXJFpwgs9qBsedjITvgC9aIqywDSt+mbQ8yHZkYVerX0N85Nq+gyPPttXP4+0MhSOvGfuECSAYeSZvJTc+bwIcsMFhaTx8UATc+qUIdQLXf0bgjZ0XbAR8wemh9HXa8VvdFcYmSK/yH+YGJX06EDXw1guUbVnxao9arYSGf7/sIeGsyGi8oklKZQ5ARRqv3XrUmi6owcep80+9vbDOPGCZ+tA13eKAEH7CDA5t61HJ2d2pq1XxZtGMWyx1p3gZTC3PuOGbI56Eb4N3kPZDRDCJ7DPcxuI4rvxyHc/hLzYAbiFKDfhoy0uAERyyrd4xJ2WgyKMMdzW0eP/0U55WpZI0PRgsU5cAMjRnTSNRzWHkrOKUauy2fqmncLZ9f7Jku0vBiESgvx+RoiuZ8OdjrlGsbHfEKLSi9wmgg1DgSqsQNM4vadpXPZvpM/8c01+yqg==
    client_secret: AgCn1vm1fOFeuWTjoVaR59Ap6HYWMu/IoIuws2BOi6sWWP2ZDnSxounf5ldQeG+Kh+Yl+FymcS7h/CxW0jmym5N2ACEgxaJ2IKH574dzgKyEcA1leCOWX34WCDc0KpDcqNVKI/MLbSkurd4LBnCWNWUIDpSTT5cwfAwCT3AdUxdVT6AqkWdM17jNjm2jTGUHgC/1Catw3hq8OwOfbDhNK4ZWehmLJ0qO3ndjACjSua8+9Yb+syio8RuE2SjS8d5SEmmg5RVRwL3Y/xvVylDKoip1K27crfqz1yc/UOhuBmvsE1rsRbWGt/wS2bf3sT3j+Zk9ZCWUL/q8xG2P21dS7vC/QSckTpUMSYz6dS4AFiFURsQQMipgYrjT+D1fjV2n9uPR97WNJiuZMPWeel/ii4Kev9jEpDZbN1kBo6szDFKHQU5pkcvF6J3MyfN+fncXBHiSggy2DKGIdyLjovTyGTs0kNNGke+oFk7FMC0MTuaq/J0VTABnIQrEBGy+Qo09xCdgk3ywvKn2B9GBfxGeR10N2OxHEwrjOCQBTIaIpD2MDPwrSCLKM1Ni7b1qCx5e9Y0dZPJqOTATcYtoHfoQT1mQ7FEuBokmI4UMvuvAcZF0xzqCrmQQu3DfOWeI8hDpvxU4cIFvDoEQG3/NzbAx5lL99Sta1mrobBRiwhDfBp1jm1Xb9BSs8RC91RlqiK0B2guZSUvMk/sIZBEDWXpIuAOnOBmHJTAf467KEbM2uYYKljrku+34aZhf1fJBL45ZmKs7xUxOdKOoLreSla6tSkE=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
