# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: 1.x.x
  install:
    crds: Create
  interval: 1m
  upgrade:
    crds: CreateReplace
