---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: amify
  namespace: monitoring
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/murtaza-u/amify
