---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: amify-secret
  namespace: monitoring
spec:
  encryptedData:
    AMIFY_NTFY_AUTH_PASSWORD: AgC37N4lm/E0+NRHWHJfZjBYWGtec+tB3xpCQXkKM52PbNIDpOkjaLOp58Gjaca3EiE/4Tj5nDvAfMUGpwGkAemjTLqeYf9BYKdZCkHGEg+uSSuXxzvh7o7Iyfu2BY8HO/7uvCGAft7s0DYvWFxEWVWk8kdFXtvDWvVGBl/A7ZLx8XAQZwEfx6AUmT0lj3Bq3ltpAMmiL6IO3DvVmSwR8KUZnf9DksmoWqCPgsg/XBW7vCe/dzcaqH6v9PybyzvNpVxMdL7tkKlSaluIJkdRuHOelpHSfm+NsBfVQ5QbLyQN78CTJYazCVTpVobbSsKbdxhl+08GLNT8df/Ngmyiw/fo5ar+FFbcdu6MNRIaFWehslISrSAYbBlur5ZObyY8grrQLcVvjpFQOrAw+QPz7q+aFxZx8FeUK/N55yVfSidvxZtRxdbHVmiV/2FdPypjaxhqK5UTYdr3AVyVb+396EbaNiBXoTJwH6RP//ysWKdtJyZEQS+z3dkVO7gscab01d6qF/QiKt4WN4Pc51UuxZYmFfYVNBC1oRUhMpIpKEjrlZtb9CKCl4L+3QsH7GQPElVNsiAUQM39HfhWOZ5WsZwTDR922JM88k/tTTXiZ32U/kZfPxS1pkiaFZxjz1G2aiLjvYsicZkwAXeAbgAD4rJvn/kctCneded6X77qVE/AaCsRxL3DbBAJXP3J4ubZ75DwgeXQoLjYJ4tfUJFwS1jRHFNf+8FFZ9VrsORyj150CNwr+XKylSk/Wq86BwmvbrECupqVQ2BoCEAxbqQBRFxrERs=
    AMIFY_NTFY_AUTH_USERNAME: AgCgZ4bYsmBorapuSto53Jcylc3MUTX+rN8XgYhWL421IjFSYmHXarE04Gu7HWa40ZrRt2n1Zof1We/446UzFCrHtEkTr+mbWkU4ksjUyozoHM2x7t/R4fs12YbmIb4/6rOi3l9ipbXjQVGKXKpstQ5iJGS3eq6rRjF/BY+acGzvENJWZ9IorvR+llS1eMmIAk+mX1+F2c3go9k6SAdW2WCs30PIbiCz3taXOMvlYBUNMokAOwc/y+78JtczSxDzIj/YiZMPOR4urUC3HnOnkhn1N+mu9swVVHL3NZKSVldOVPrvOvzreyg0U52vYexjHQ6t3b9nX4bzJynZFBDaAyCWu4vMOXSkyz1yUxAdL8hs8V3wPWLoRVIrmIcjwF6plSuUgtDpInL/CYQeruorxyr840lYsZSxJDXfFXmKWC2wr2m5KgZt5JnPTyIYXJI/paAlKcOpFc3hFzJrc7et11a6efPabMjuA2REkz++kw05vrS9Jl9Wkg4yEIDZLYvLSOTD2zrM2t8NWl0RCROyK9H31g055Emy2j63f2YVi7efa1swmACgHFFbLZr+ovloHEsjlzCbhKePH+XQnCsOadwunznW227W1jiQgcEOVjG/wBgrmPvGwEtHIBcAd7+LkInUF2sL5Ue5doIZXWNWLC1RL1b+wWY54iDOZWaYM74tTtcEBVLrs8oQTkgTLnPtZqc3ChW2vw==
  template:
    metadata:
      creationTimestamp: null
      name: amify-secret
      namespace: monitoring
    type: Opaque
