---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: amify-secret
  namespace: monitoring
spec:
  encryptedData:
    AMIFY_NTFY_AUTH_PASSWORD: AgBaOmuoPIY0CK3gJlC0KsMWZbXh3c40K6TltRGJ48unq/ciPHMwp8+S0qU+jE8PCIOkaQeOLDd38uoODJovahv+sTq5TPlRM8h1PuQbNvz6jXDDANrsdmz26Diztung6tCDQRl2SzEMZk4VVQe8BPAjW0L5sMJfRkqMSQsWtdT6qu+0DSqBXf3aDUPdXTeGy+EAkKrt/sVvVniEHiW0egyko7hMKvfrdSf3OthD0suerEThRpng4W8WyCQZKJQVieOgUJWUvoG6EPrQKFFpd8R7+elWC6pNIDsZbGij7KaTPL8e8ByB20aEDWM6ACNCru8m+TPfNCK+h0YX7Hpd4TG5ea9cJngznAWw2dCywVMr09WKRNleSJyfhgfxKj4poZxK/Tn5tueCxCu53pmZYSvlEHOfLx6kPhOzupgc+Y1jngfH6hUSK198il7qFvld0EdbMITPg1CEl37MtfwIKYZqCOCZvwV1iXyzc9IYyf0h6BUEUO65Zat/iTwWBtPhZMfDrpTo6socMCfMrQisP3InJ4rnxg0TEHo8I74nJZAZmXihjK5qsYsMO1FUxREd3KdiBp36CrLWbX7ZVgpZlcB3/vqRbkl3MUibBbo+dhz4QcSJoscKaWVEf1ZZgMUTtWKRSOhQZf9SV0RgTujD3CXYn94uz7Zi0J7SLfbInBdgm9xe9qe2jxslTM3d4pDc8b30v3k8dPRjN8OFLHH1CsdPINYJKK+fUDRzTYmK1/OppNOk0F8bJatP+lTdnDb4mmk0P0JyifNjUTXKibI9/54W3fc=
    AMIFY_NTFY_AUTH_USERNAME: AgBOUYjSfDhBQmWGD+JtGJKPFKKoPsTQFkAner8rvYYD/a0KhWu+9kxI5b4MHZztlpD5Q1P2Cz/X0YZlG4SPQlsBlb7lllaXuTiRk5mmj0cupi68+auN8+ctLqZUu7PAdPTT4TqiSFJ470Toaakm5GZnsVJyX51PcsEYPcPBpqBD8p+bQgxTgRAjxL4F5b7yD5mpztNdKDo0K5AUF8byMIBQ0NU2py/0LkuKk+/5A0FUSz+eiD1P6Ygzs9TC+MNf2XKSLqWOjoYWX8A8yU6yKiBxncxui7a+jOri51jW2WqGloj1a4DhpCoyuf7Q4pE5mpH1gbJHCmUsC0aoBh7R5f4s6ZmglX4MYTlshnxI606QHdvorX/jRtFF5D+WJak9pz9aLt/s3rvMEPfxyuQqRwaVT09lDRYo2xIGn2vQvjTGxujLiZjkUvVusMY7Tr5pLy+tCUX7euJjabERt6ZNxg7xdAdpwRtADR8OKbgcxTkq4/E3cSHh+GxpSDPFL/+00weHoLjr7EuImKIUlHhlkLo+4DsYXJ4rUxYrqPHWygguV7LO8jS3OIcgpiTVtP3Vsu2mDMHF06HaOAc3Oly7HkdGW9GNEPRZ3Butvddh4IIbLA6zQLIu0Izo3SyP/K/DdCvKB7ZE9Yr8ix611r2FWKXHgkZ2jhqssC2ocgz+RSwupjuY+HfnhxXH05Frj7zKzYMrmHuACNw=
  template:
    metadata:
      creationTimestamp: null
      name: amify-secret
      namespace: monitoring
    type: Opaque
