---
name: NixOS continuous deployment pipeline

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "hosts/**"

jobs:
  shiganshina:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Create SSH config directory
        run: 'mkdir -p ~/.ssh'

      - name: Write custom SSH config from secret
        run: 'echo "${{ secrets.SSH_CONFIG_FILE }}" > ~/.ssh/config'

      - name: Configure known hosts
        run: 'echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts'

      - name: Set SSH_CONFIG_FILE environment variable
        run: 'export SSH_CONFIG_FILE=~/.ssh/config'

      - name: Install nix
        uses: cachix/install-nix-action@v30

      - name: Rebuild the new configuration and push it to remote
        run: |
          nix develop --impure --command nixos-rebuild \
            --flake .#shiganshina \
            --target-host shiganshina \
            --use-remote-sudo \
            switch
  base:
    runs-on:
      - nixos
      - node-base
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Create SSH config directory
        run: 'mkdir -p /home/$USER/.ssh'

      - name: Write custom SSH config from secret
        run: 'echo "${{ secrets.SSH_CONFIG_FILE }}" > /home/$USER/.ssh/config'

      - name: Configure known hosts
        run: 'echo "${{ secrets.SSH_KNOWN_HOST }}" > /home/$USER/.ssh/known_hosts'

      - name: Set SSH_CONFIG_FILE environment variable
        run: 'export SSH_CONFIG_FILE=/home/$USER/.ssh/config'

      - name: Install nix
        uses: cachix/install-nix-action@v30

      - name: Rebuild the new configuration and push it to remote
        run: |
          nix develop --impure --command nixos-rebuild \
            --flake .#base \
            --target-host base \
            --use-remote-sudo \
            switch
